### ISSUE TITLE
Compatibility with NC 24.0.2?

### ISSUE THREAD

**Issue by AnAnalogGuy** [nextcloud/backup#342]
The app is marked "not tested" and ist getting deactivad while updating to NC 24.0.2. 
Do we already know if it's working or if an update is required? If the latter: Any related plans?

**Comment by AnAnalogGuy** [comment]
Could relate to this one https://github.com/nextcloud/backup/issues/329

**Comment by AnAnalogGuy** [comment]
Is anyone using the Backup app with 24.0.2?
Any feedback from the developers?

**Comment by Omemanti** [comment]
I tried it, but after moving to 24 it looks broken.. (it worked at some time on 23 but not sure if it broke on 1.0.5 or 1.0.6)

**Comment by ph00lt0** [comment]
HAHAHHAAHAHAHAHAH howwwww!!!?? They really can't seem to get their shit together at nextcloud do they.

**Comment by AnAnalogGuy** [comment]
> HAHAHHAAHAHAHAHAH howwwww!!!?? They really can't seem to get their shit together at nextcloud do they.
That's not really a helpful comment.

**Comment by ph00lt0** [comment]
I am fully agreeing, but the level of amateurish deployments has gotten worse and worse. At some point you would think a project would grow over its infancy. I have been here from the start of Nextcloud and really really hoped it would become something great but I just really can't say it is after all these years. The community relies on dirty hacks to solve sync issues, incompatible apps, unreliable backups and marketing encryption rather than actual security. All the time they launch new apps to hype but don't properly maintain the core. Get the basics right.

**Comment by AnAnalogGuy** [comment]
I can't judge on what @ph00lt0 wrote and this is not the right place for a general feedback on the development principles in the Nextcloud project. 

However, one aspect in relation to this issue I find very improvable: For a serious software project, FOSS or not, it should be a best practise to communicate, in this case, on every new NC release, just drop a note if the Backup App has been tested with or not, if there are any issues known and if yes, if there any plans to fix it or not. But not communicating and not reacting and leaving the community in the dark, specially with such a core aspect of system operation as backup is, really is a bad style, not to say, not professional. Please improve. 

I'm closing this issues as there obv is no one from the project caring about this issue and i will have to find another solution.
