### ISSUE TITLE
Incompatible with Hetzner Storage Share

### ISSUE THREAD

**Issue by karlemilnikka** [nextcloud/backup#423]
The app is currently incompatible with Hetzner’s Storage Share instances, even after Hetzner added support for external storage. When storing app data locally, I get an error message saying “unable to fetch app data”. When storing app data on external storage, the backups are never completed. Disabling compression and encryption does not solve the issue.

I’ve reported the issue to Hetzner. They are aware of the issue and are trying to find a workaround on their end.

**Comment by ksoeren** [comment]
Relates to #440

**Comment by DirkHeinke** [comment]
As #440 is now closed and merged, should this now work on the Storage Share? #604 looks like Richard successful ran the backup app, but is not able to access the local backups.

**Comment by ksoeren** [comment]
Hi there,

Unfortunately we are still unable to fully support the backup app. We found several other issues with it during our testing:
- Uploading to an external resource fails due to an incompatibility with files_versions (see https://github.com/nextcloud/backup/issues/434 . This was also confirmed by our tests)
- The runtime to create and pack a backup is extremely high (we measure about 5 hours per 100GB during the packing process).
- The packing process requires a large amount of CPU and RAM resources (which we cannot reasonably provide to all Storage Share instances as they are hosted on shared systems).

Especially points 2 and 3 make it impossible for us to fully support the backup app and offer it as a cron job. 
However, if it remains in reasonable amounts, you can request the manual execution of the backup creation OCC commands via a ticket.

**Comment by karlemilnikka** [comment]
Thank you very much for the update, @ksoeren.
